#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

FW_DIR="$DESTDIR/lib/firmware"

# install Afatech AF9013 firmware
mkdir -p $FW_DIR
  cp af9013/* $FW_DIR

# install Afatech AF9015 firmware
mkdir -p $FW_DIR
  cp af9015/* $FW_DIR

# install AV7110 firmware
mkdir -p $FW_DIR
  cp av7110/* $FW_DIR

# install Avertv A800 firmware
mkdir -p $FW_DIR
  cp avertv-a800/* $FW_DIR

# install BCM3510 firmware
mkdir -p $FW_DIR
  cp bcm3510/* $FW_DIR

# install Conexant Bluebird firmware
mkdir -p $FW_DIR
  cp bluebird/* $FW_DIR

# install Conexant cx231xx firmware
mkdir -p $FW_DIR
  cp cx231xx/* $FW_DIR

# install Conexant cx23418 firmware
mkdir -p $FW_DIR
  cp cx23418/* $FW_DIR

# install Conexant cx23885 firmware
mkdir -p $FW_DIR
  cp cx23885/* $FW_DIR

# install Conexant cx24116 firmware
mkdir -p $FW_DIR
  cp cx24116/* $FW_DIR

# install Conexant cx25840 firmware
mkdir -p $FW_DIR
  cp cx25840/* $FW_DIR
