#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2011 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

FW_DIR="$DESTDIR/lib/firmware"

# install Afatech AF9013 firmware
mkdir -p $FW_DIR
  cp af9013/* $FW_DIR

# install Afatech AF9015 firmware
mkdir -p $FW_DIR
  cp af9015/* $FW_DIR

# install AV7110 firmware
mkdir -p $FW_DIR
  cp av7110/* $FW_DIR

# install Avertv A800 firmware
mkdir -p $FW_DIR
  cp avertv-a800/* $FW_DIR

# install BCM3510 firmware
mkdir -p $FW_DIR
  cp bcm3510/* $FW_DIR

# install Conexant Bluebird firmware
mkdir -p $FW_DIR
  cp bluebird/* $FW_DIR

# install Conexant cx231xx firmware
mkdir -p $FW_DIR
  cp cx231xx/* $FW_DIR

# install Conexant cx23418 firmware
mkdir -p $FW_DIR
  cp cx23418/* $FW_DIR

# install Conexant cx23885 firmware
mkdir -p $FW_DIR
  cp cx23885/* $FW_DIR

# install Conexant cx24116 firmware
mkdir -p $FW_DIR
  cp cx24116/* $FW_DIR

# install Conexant cx25840 firmware
mkdir -p $FW_DIR
  cp cx25840/* $FW_DIR

# install dib0700 firmware
mkdir -p $FW_DIR
  cp dib0700/* $FW_DIR

# install dibusb firmware
mkdir -p $FW_DIR
  cp dibusb/* $FW_DIR

# install ds3000 firmware
mkdir -p $FW_DIR
  cp ds3000/* $FW_DIR

# install dtt200u firmware
mkdir -p $FW_DIR
  cp dtt200u/* $FW_DIR

# install dw2104 firmware
mkdir -p $FW_DIR
  cp dw2104/* $FW_DIR

# install ec168 firmware
mkdir -p $FW_DIR
  cp ec168/* $FW_DIR

# install lgs8gxx firmware
mkdir -p $FW_DIR
  cp lgs8gxx/* $FW_DIR

# install or51132 firmware
mkdir -p $FW_DIR
  cp or51132/* $FW_DIR

# install or51211 firmware
mkdir -p $FW_DIR
  cp or51211/* $FW_DIR

# install s2250 firmware
mkdir -p $FW_DIR
  cp s2250/* $FW_DIR

# install s6xx firmware
mkdir -p $FW_DIR
  cp s6xx/* $FW_DIR

# install sms1xxx firmware
mkdir -p $FW_DIR
  cp sms1xxx/* $FW_DIR

# install tlg2300 firmware
mkdir -p $FW_DIR
  cp tlg2300/* $FW_DIR

# install ttusb-budget firmware
mkdir -p $FW_DIR/ttusb-budget
  cp ttusb-budget/* $FW_DIR/ttusb-budget

# install umt-010 firmware
mkdir -p $FW_DIR
  cp umt-010/* $FW_DIR

# install vp702x firmware
mkdir -p $FW_DIR
  cp vp702x/* $FW_DIR

# install vp7045 firmware
mkdir -p $FW_DIR
  cp vp7045/* $FW_DIR

# install wt220u firmware
mkdir -p $FW_DIR
  cp wt220u/* $FW_DIR

# install xc5000 firmware
mkdir -p $FW_DIR
  cp xc5000/* $FW_DIR
